version: '3.8'

services:

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - django

  django:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: django
    command: >
      bash -c "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/eye_of_chubaka
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  celery_worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: celery_worker
    command: /start-worker
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - django

  celery_beat:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: celery_beat
    command: /start-beat
    depends_on:
      - celery_worker

  celery_flower:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: celery_flower
    command: /start-flower
    volumes:
      - .:/django
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    ports:
      - "5555:5555"
    depends_on:
      - celery_beat

  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: