# Generated by Django 4.2.6 on 2023-10-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default='', max_length=12, unique=True)),
                ('total_asks_volume', models.IntegerField(default=0)),
                ('total_bids_volume', models.IntegerField(default=0)),
                ('limit3', models.FloatField(default=0.0)),
                ('limit5', models.FloatField(default=0.0)),
                ('limit8', models.FloatField(default=0.0)),
                ('limit30', models.FloatField(default=0.0)),
            ],
        ),
    ]
