# Generated by Django 4.2.6 on 2023-10-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depth',
            name='id',
        ),
        migrations.AlterField(
            model_name='depth',
            name='symbol',
            field=models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
