# Generated by Django 4.2.6 on 2023-10-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_depth_id_alter_depth_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funding',
            fields=[
                ('symbol', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('exchangeLogo', models.CharField(default='', max_length=120, unique=True)),
                ('binance_funding', models.IntegerField(default=0)),
                ('okx_funding', models.IntegerField(default=0)),
                ('dydx_funding', models.IntegerField(default=0)),
                ('bybit_funding', models.IntegerField(default=0)),
                ('gate_funding', models.IntegerField(default=0)),
                ('bitget_funding', models.IntegerField(default=0)),
                ('coinex_funding', models.IntegerField(default=0)),
                ('bingx_funding', models.IntegerField(default=0)),
                ('other_exchange_sum', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='depth',
            name='exchangeLogo',
            field=models.CharField(default='', max_length=120, unique=True),
        ),
    ]
