# Generated by Django 4.2.6 on 2023-10-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_funding_exchangelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='binance_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='bingx_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='bitget_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='bybit_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='coinex_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='dydx_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='gate_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='okx_funding',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='funding',
            name='other_exchange_sum',
            field=models.FloatField(default=0.0),
        ),
    ]
