# Generated by Django 4.2.6 on 2023-10-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_funding_binance_funding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depth',
            name='exchangeLogo',
        ),
    ]
