# Generated by Django 4.2.6 on 2023-10-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_depth_exchangelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingFinal',
            fields=[
                ('symbol', models.CharField(default='', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('binance_positive', models.IntegerField(default=0)),
                ('binance_balance', models.IntegerField(default=0)),
                ('binance_negative', models.IntegerField(default=0)),
                ('other_ex_positive', models.IntegerField(default=0)),
                ('other_ex_balance', models.IntegerField(default=0)),
                ('other_ex_negative', models.IntegerField(default=0)),
            ],
        ),
    ]
