# Generated by Django 4.2.6 on 2023-10-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_fundingfinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='depth',
            name='type',
            field=models.CharField(default='Depth', max_length=12),
        ),
        migrations.AddField(
            model_name='funding',
            name='type',
            field=models.CharField(default='Funding', max_length=12),
        ),
        migrations.AddField(
            model_name='fundingfinal',
            name='type',
            field=models.CharField(default='FundingFinal', max_length=12),
        ),
    ]
